packages:
    - apps/*
    - packages/*
    - scripts

# Pre approve builds
onlyBuiltDependencies:
    # For wrangler (cf worker)
    - esbuild
    - workerd
    - sharp

catalog:
    hono: 4.12.23
    "@changesets/cli": "^2.31.0"
