name: "CI: Production"

on:
    workflow_dispatch:
        inputs:
            target:
                description: "What to build"
                required: true
                default: "all"
                type: choice
                options:
                    - all
                    - server
                    - web
    push:
        branches:
            - master

permissions:
    contents: read

jobs:
    changes:
        name: "Check File Changes"
        runs-on: ubuntu-latest

        outputs:
            server: ${{ steps.filter.outputs.server }}
            web: ${{ steps.filter.outputs.web }}

        steps:
            - name: "Checkout"
              uses: actions/checkout@v4

            - name: "Check file changes"
              uses: dorny/paths-filter@v4
              id: filter
              with:
                  filters: |
                      server:
                          - "apps/server/**"
                          - "packages/types/**"
                          - "pnpm-lock.yaml"
                          - "pnpm-workspace.yaml"
                      web:
                          - "apps/web/**"
                          - "packages/types/**"
                          - "pnpm-lock.yaml"
                          - "pnpm-workspace.yaml"

    build-unbound:
        name: "Build: Unbound App"
        needs: changes
        runs-on: ubuntu-latest
        environment:
            name: production

        if: ${{ (
            github.event_name == 'push' && (needs.changes.outputs.server == 'true' || needs.changes.outputs.web == 'true')
            ) || (
            github.event_name == 'workflow_dispatch' && (inputs.target == 'all' || inputs.target == 'server')
            ) }}

        steps:
            - name: "Checkout"
              uses: actions/checkout@v4

            - name: "Setup environment"
              uses: ./.github/actions/setup

            - name: "Build web CSS"
              working-directory: apps/web
              run: pnpm run build

            - name: "Adjust wrangler config before deploy"
              working-directory: apps/server
              run: |
                  perl -0777 -pe 's|/\*.*?\*/||gs; s|//[^\n]*||g; s/,(\s*[}\]])/\1/g' wrangler.jsonc \
                    | jq '.vars = {}' > wrangler.json
                  rm wrangler.jsonc

            - name: "Deploy to Cloudflare"
              working-directory: apps/server
              env:
                  CLOUDFLARE_API_TOKEN: ${{ secrets.CF_API_SECRET }}
              run: pnpm run deploy:cf
