name: "PR Check"

on:
    pull_request:

permissions:
    contents: read
    pull-requests: read

jobs:
    changes:
        uses: ./.github/workflows/check-changes.yml

    lint-server:
        name: "Run lint: Server"
        needs: changes
        if: ${{ needs.changes.outputs.server == 'true' }}
        runs-on: ubuntu-latest

        steps:
            - name: "Checkout"
              uses: actions/checkout@v4

            - name: "Setup environment"
              uses: ./.github/actions/setup

            - name: "Lint"
              working-directory: apps/server
              run: pnpm run lint

    lint-web:
        name: "Run lint: Web"
        needs: changes
        if: ${{ needs.changes.outputs.web == 'true' }}
        runs-on: ubuntu-latest

        steps:
            - name: "Checkout"
              uses: actions/checkout@v4

            - name: "Setup environment"
              uses: ./.github/actions/setup

            - name: "Lint"
              working-directory: apps/web
              run: pnpm run lint
